name: Status Update Notification

on:
  repository_dispatch:
    types: [status-update-notification]

jobs:
  notify-status-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get workflow status
        id: workflow-status
        run: |
          # Extract data from repository dispatch payload
          echo "status=${{ github.event.client_payload.status || 'unknown' }}" >> $GITHUB_OUTPUT
          echo "workflow_name=${{ github.event.client_payload.workflow_name || 'unknown' }}" >> $GITHUB_OUTPUT
          echo "repository=${{ github.event.client_payload.repository || github.repository }}" >> $GITHUB_OUTPUT
          echo "run_id=${{ github.event.client_payload.run_id || 'unknown' }}" >> $GITHUB_OUTPUT
          echo "context=${{ github.event.client_payload.context || 'unknown' }}" >> $GITHUB_OUTPUT
          echo "description=${{ github.event.client_payload.description || 'Status update notification' }}" >> $GITHUB_OUTPUT
          echo "app_name=${{ github.event.client_payload.app_name || 'unknown' }}" >> $GITHUB_OUTPUT
          
      - name: Send notification
        if: steps.workflow-status.outputs.status != 'skipped'
        run: |
          echo "Status Update Notification"
          echo "========================"
          
          echo "Workflow: ${{ steps.workflow-status.outputs.workflow_name }}"
          echo "Status: ${{ steps.workflow-status.outputs.status }}"
          echo "Repository: ${{ steps.workflow-status.outputs.repository }}"
          echo "Run ID: ${{ steps.workflow-status.outputs.run_id }}"
          echo "Context: ${{ steps.workflow-status.outputs.context }}"
          echo "Description: ${{ steps.workflow-status.outputs.description }}"
          echo "App: ${{ steps.workflow-status.outputs.app_name }}"
          
          echo "Event: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          
          # Add your notification logic here
          # Examples:
          # - Send Slack notification
          # - Send email
          # - Send Discord webhook
          # - Update external status page
          
          echo "Notification sent successfully!"